spring:
  datasource:
    url: jdbc:mysql://localhost:3306/creditbd
    username: root
    password: kevv123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
