spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditbd
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
